//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ress {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetaLolBuild.UI.Views.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zırh.
        /// </summary>
        public static string armor {
            get {
                return ResourceManager.GetString("armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldırı Gücü.
        /// </summary>
        public static string attackdamage {
            get {
                return ResourceManager.GetString("attackdamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldırı Hızı.
        /// </summary>
        public static string attackspeedoffset {
            get {
                return ResourceManager.GetString("attackspeedoffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şampiyonlar.
        /// </summary>
        public static string Champions {
            get {
                return ResourceManager.GetString("Champions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aradığınız Sayfa Bulunamadı ! .
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can.
        /// </summary>
        public static string hp {
            get {
                return ResourceManager.GetString("hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Yenileme.
        /// </summary>
        public static string hpregen {
            get {
                return ResourceManager.GetString("hpregen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hareket Hızı.
        /// </summary>
        public static string movespeed {
            get {
                return ResourceManager.GetString("movespeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seviye başına.
        /// </summary>
        public static string perlevel {
            get {
                return ResourceManager.GetString("perlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetenekler.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kostümler.
        /// </summary>
        public static string Skins {
            get {
                return ResourceManager.GetString("Skins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyü Direnci.
        /// </summary>
        public static string spellblock {
            get {
                return ResourceManager.GetString("spellblock", resourceCulture);
            }
        }
    }
}
